Algoritmo "semnome"




Var
 nota1, nota2, nota3, nota4, media : real
Inicio


      escreva ("Informe a valor 1: ")
      leia (nota1)
      escreva ("informe a valor 2: ")
      leia (nota2)
      escreva ("informe a valor 3: ")
      leia (nota3)
      Escreva ("informe a valor 4: ")
      leia (nota4)
      
      somar =  (valor1 + valor2 + valor3 + valor4)



                     
          
          


Fimalgoritmo